//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace akiss.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AboutPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AboutPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("akiss.Resources.AboutPage", typeof(AboutPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admissions.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string find {
            get {
                return ResourceManager.GetString("find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string started {
            get {
                return ResourceManager.GetString("started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT Program.
        /// </summary>
        public static string advantages {
            get {
                return ResourceManager.GetString("advantages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lessons.
        /// </summary>
        public static string taklif {
            get {
                return ResourceManager.GetString("taklif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Team.
        /// </summary>
        public static string f1 {
            get {
                return ResourceManager.GetString("f1", resourceCulture);
            }
        }
        public static string f2 {
            get {
                return ResourceManager.GetString("f2", resourceCulture);
            }
        }
        public static string f3 {
            get {
                return ResourceManager.GetString("f3", resourceCulture);
            }
        }
        public static string f4 {
            get {
                return ResourceManager.GetString("f4", resourceCulture);
            }
        }
        public static string f5 {
            get {
                return ResourceManager.GetString("f5", resourceCulture);
            }
        }
        public static string f6 {
            get {
                return ResourceManager.GetString("f6", resourceCulture);
            }
        }
        public static string f7 {
            get {
                return ResourceManager.GetString("f7", resourceCulture);
            }
        }
        public static string f8 {
            get {
                return ResourceManager.GetString("f8", resourceCulture);
            }
        }
        public static string f9 {
            get {
                return ResourceManager.GetString("f9", resourceCulture);
            }
        }
        public static string f10 {
            get {
                return ResourceManager.GetString("f10", resourceCulture);
            }
        }
    }
}
