//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace akiss.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdmissionFormComponent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdmissionFormComponent() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("akiss.Resources.AdmissionFormComponent", typeof(AdmissionFormComponent).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string fullname {
            get {
                return ResourceManager.GetString("fullname", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Our Team.
        /// </summary>
        public static string grade {
            get {
                return ResourceManager.GetString("grade", resourceCulture);
            }
        }
        public static string olimpiad {
            get {
                return ResourceManager.GetString("olimpiad", resourceCulture);
            }
        }
        public static string subject {
            get {
                return ResourceManager.GetString("subject", resourceCulture);
            }
        }
        public static string number1 {
            get {
                return ResourceManager.GetString("number1", resourceCulture);
            }
        }
        public static string addres {
            get {
                return ResourceManager.GetString("addres", resourceCulture);
            }
        }
        public static string application {
            get {
                return ResourceManager.GetString("application", resourceCulture);
            }
        }
        public static string facluty {
            get {
                return ResourceManager.GetString("facluty", resourceCulture);
            }
        }
        public static string aniqfanlar {
            get {
                return ResourceManager.GetString("aniqfanlar", resourceCulture);
            }
        }
        public static string gumanitarfanlar {
            get {
                return ResourceManager.GetString("gumanitarfanlar", resourceCulture);
            }
        }
        public static string hozirgimaktab {
            get {
                return ResourceManager.GetString("hozirgimaktab", resourceCulture);
            }
        }
        public static string shahar {
            get {
                return ResourceManager.GetString("shahar", resourceCulture);
            }
        }
        public static string tuman {
            get {
                return ResourceManager.GetString("tuman", resourceCulture);
            }
        }
        public static string maktabraqami {
            get {
                return ResourceManager.GetString("maktabraqami", resourceCulture);
            }
        }
        public static string habar {
            get {
                return ResourceManager.GetString("habar", resourceCulture);
            }
        }
    }
}
