//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace akiss.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FooterComponent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FooterComponent() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("akiss.Resources.FooterComponent", typeof(FooterComponent).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admissions.
        /// </summary>
        public static string addressStreet{
            get {
                return ResourceManager.GetString("addressStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string addressBuilding {
            get {
                return ResourceManager.GetString("addressBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT Program.
        /// </summary>
        public static string province {
            get {
                return ResourceManager.GetString("province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lessons.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Team.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Our Team.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Our Team.
        /// </summary>
        public static string admission {
            get {
                return ResourceManager.GetString("admission", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Our Team.
        /// </summary>
        public static string team {
            get {
                return ResourceManager.GetString("team", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Our Team.
        /// </summary>
        public static string lessons {
            get {
                return ResourceManager.GetString("lessons", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Our Team.
        /// </summary>
        public static string DesignedBy {
            get {
                return ResourceManager.GetString("DesignedBy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Our Team.
        /// </summary>
        public static string pages {
            get {
                return ResourceManager.GetString("pages", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Our Team.
        /// </summary>
        public static string uz {
            get {
                return ResourceManager.GetString("uz", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Our Team.
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Our Team.
        /// </summary>
        public static string ru {
            get {
                return ResourceManager.GetString("ru", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Our Team.
        /// </summary>
        public static string addressRegion {
            get {
                return ResourceManager.GetString("addressRegion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Our Team.
        /// </summary>
        public static string it {
            get {
                return ResourceManager.GetString("it", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Our Team.
        /// </summary>
        public static string weareinSM {
            get {
                return ResourceManager.GetString("weareinSM", resourceCulture);
            }
        }
    }
}
